//
//  DBCheckViewController.swift
//  DemoProjectApp
//
//  Created by nabushan-pt5611 on 22/09/22.
//

import UIKit

struct DBContents {
    
    let reminders: [Reminder] = [
        Reminder(date: "2023-02-05", time: "10:05:00", medicineName: "Alegre", medicineBody: "This is a Gentle reminder to take Dolo 650 before Breakfast.", medicineType: "pill", foodIntervalToTake: .dinner, schedule: .before, userId: 1),
        Reminder(date: "2023-02-30", time: "10:05:00", medicineName: "Dolo 650", medicineBody: "This is a Gentle reminder to take Dolo 650 before Breakfast.", medicineType: "pill", foodIntervalToTake: .lunch, schedule: .after, userId: 2),
        Reminder(date: "2022-02-26", time: "10:05:00", medicineName: "Paracetamol", medicineBody: "This is a Gentle reminder to take Paracetamol before Breakfast.", medicineType: "pill", foodIntervalToTake: .breakFast, schedule: .before, userId: 1),
        Reminder(date: "2023-02-09", time: "11:30:00", medicineName: "Citrzene", medicineBody: "This is a Gentle reminder to take Citrzene after Lunch.", medicineType: "pill", foodIntervalToTake: .lunch, schedule: .after, userId: 2),
        Reminder(date: "2023-02-19", time: "11:30:00", medicineName: "Diegene", medicineBody: "This is a Gentle reminder to take Diegene after Dinner.", medicineType: "tonic", foodIntervalToTake: .dinner, schedule: .after, userId: 1),
        Reminder(date: "2023-02-15", time: "11:30:00", medicineName: "Insulin", medicineBody: "This is a Gentle reminder to take Insulin before BreakFast.", medicineType: "vaccine", foodIntervalToTake: .breakFast, schedule: .before, userId: 2),
        Reminder(date: "2023-02-12", time: "11:30:00", medicineName: "Losartan", medicineBody: "This is a Gentle reminder to take Losartan before Lunch.",medicineType: "pill", foodIntervalToTake: .lunch, schedule: .before, userId: 1),
    ]
    
    let doctorVedioCallTimings: [DoctorTiming] = [
        DoctorTiming(id: 0,
                     monday: "09:00 AM - 12:30 PM",
                     tuesday: "09:00 AM - 10:30 AM",
                     wednesday: "11:00 AM - 12:30 PM",
                     thursday: "10:30 AM - 12:00 PM",
                     friday: "08:00 AM - 09:30 AM",
                     saturday: "09:00 AM - 12:30 PM",
                     sunday: "No Slots Available"),
        
        DoctorTiming(id: 1,
                     monday: "08:00 AM - 09:30 AM",
                     tuesday: "08:00 AM - 08:30 AM",
                     wednesday: "09:00 AM - 10:30 AM",
                     thursday: "09:00 AM - 11:30 AM",
                     friday: "11:00 AM - 12:30 PM",
                     saturday: "09:00 AM - 11:30 AM",
                     sunday: "08:00 AM - 11:00 AM")
    ]
    
    let doctorHospitalVisitTimings: [DoctorTiming] = [
        DoctorTiming(id: 0,
                     monday: "12:30 PM - 14:00 PM",
                     tuesday: "14:30 PM - 16:00 PM",
                     wednesday: "15:30 PM - 17:30 PM",
                     thursday: "13:30 PM - 16:30 PM",
                     friday: "16:30 PM - 18:30 PM",
                     saturday: "18:30 PM - 20:30 PM",
                     sunday: "19:30 PM - 20:00 PM"),
        
        DoctorTiming(id: 1,
                     monday: "12:30 PM - 15:00 PM",
                     tuesday: "17:30 PM - 19:00 PM",
                     wednesday: "14:30 PM - 16:30 PM",
                     thursday: "18:30 PM - 19:30 PM",
                     friday: "21:30 PM - 22:30 PM",
                     saturday: "22:30 PM - 23:00 PM",
                     sunday: "No Slots Available")
    ]
    
    let doctors: [Doctor] = [
        
//        Cardiologists
        Doctor(id: 1,
               name: "Dr. Vikas",
               imageName: "https://img.freepik.com/free-vector/doctor-character-background_1270-84.jpg?w=1380&t=st=1664532255~exp=1664532855~hmac=cf6ce93f6cc5a887c47459e0d275b97159f27c2d2dfc0a63cf06d9f3cfb1b888",
               designation: .cardiologist,
               experience: "5 YRS EXP",
               qualification: "MBBS, Dip. in Cardio",
               location: "Appolo CLinic, Chennai",
               languagesKnown: "English, Hindi, Telugu",
               availableForAMinimumOf: 7,
               vedioConsultationCost: 550,
               hospitalVisitCost: 550,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "Greams Road Chennai",
               videoConsultTimings: 1,
               hospitalTiming: 1,
               ratings: 4.3,
               totalNumberOfRaters: 15),
        
        Doctor(id: 2,
               name: "Dr. Subburamakrishnan P",
               imageName: "https://previews.123rf.com/images/jemastock/jemastock1702/jemastock170202798/71262969-old-man-medical-doctor-cartoon-icon-over-white-background-colorful-desing-vector-illustration.jpg",
               designation: .cardiologist,
               experience: "15 YRS EXP",
               qualification: "MD, DM (Cardiology)",
               location: "Appolo Speciality Hospitals KK Nagar, Chennai",
               languagesKnown: "English, Hindi, Tamil",
               availableForAMinimumOf: 7,
               vedioConsultationCost: 600,
               hospitalVisitCost: 600,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "80 Feet Road, KK Nagar chennai",
               videoConsultTimings: 0,
               hospitalTiming: 0,
               ratings: 3.5,
               totalNumberOfRaters: 15),
        
//        Nephrologist
        
        Doctor(id: 3,
               name: "Dr. Manoj",
               imageName: "https://previews.123rf.com/images/jemastock/jemastock1702/jemastock170202885/71263061-man-medical-doctor-cartoon-icon-over-white-background-colorful-desing-vector-illustration.jpg",
               designation: .nephrologist,
               experience: "4 YRS EXP",
               qualification: "MBBS, MD, DM Nephrology",
               location: "Kakatiya Kidney And Dialysis Hospital, Chennai",
               languagesKnown: "English, Telugu, Hindi, kannada",
               availableForAMinimumOf: 7,
               vedioConsultationCost: 300,
               hospitalVisitCost: 300,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "80 Feet Road, Egmore Chennai",
               videoConsultTimings: 0,
               hospitalTiming: 1,
               ratings: 4.2,
               totalNumberOfRaters: 15),
        
        Doctor(id: 4,
               name: "Dr. Sunil Kumar",
               imageName: "https://png.pngtree.com/png-vector/20190130/ourlarge/pngtree-cartoon-male-doctor-with-glasses-doctorelement-design-png-image_583959.jpg",
               designation: .nephrologist,
               experience: "15 YRS EXP",
               qualification: "MBBS, MD, DM Nephrology",
               location: "Appolo Multispeciality Hospitals, Chennai",
               languagesKnown: "English, Hindi, Bengali, Punjabi",
               availableForAMinimumOf: 6,
               vedioConsultationCost: 1000,
               hospitalVisitCost: 1000,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "58 Greams Road Chennai",
               videoConsultTimings: 1,
               hospitalTiming: 0,
               ratings: 3.9,
               totalNumberOfRaters: 15),
        
//        immunologists
        
        Doctor(id: 5,
               name: "Dr. Sonal Mehra",
               imageName: "https://img.freepik.com/premium-vector/female-doctor-with-stethoscope-medical-professional-therapist-illustration-cartoon-style-vector-illustration_454120-92.jpg?w=2000",
               designation: .immunologists,
               experience: "15 YRS EXP",
               qualification: "MBBA, MD (Internal Medicine), DM (Clinical Immunology & Rheumatology)",
               location: "Appolo Hospitals, Chennai",
               languagesKnown: "English, Hindi",
               availableForAMinimumOf: 5,
               vedioConsultationCost: 1500,
               hospitalVisitCost: 1200,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "58 Greams Road Chennai",
               videoConsultTimings: 1,
               hospitalTiming: 0,
               ratings: 4.0,
               totalNumberOfRaters: 15),
        
        Doctor(id: 6,
               name: "Dr. Shiva Prasad B N",
               imageName: "https://previews.123rf.com/images/jemastock/jemastock1702/jemastock170202778/71262443-man-medical-doctor-cartoon-icon-over-white-background-colorful-desing-vector-illustration.jpg",
               designation: .immunologists,
               experience: "10 YRS EXP",
               qualification: "MBBS, MD (Int. Med.), DM (Clinical Immunology), FAGE",
               location: "Appolo Hospitals, Chennai",
               languagesKnown: "English, Tamil",
               availableForAMinimumOf: 7,
               vedioConsultationCost: 650,
               hospitalVisitCost: 650,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "58 Greams Road Chennai",
               videoConsultTimings: 1,
               hospitalTiming: 1,
               ratings: 4.6,
               totalNumberOfRaters: 15),
        
//        gastroenterologist
        
        Doctor(id: 7,
               name: "Dr. Tarun John George",
               imageName: "https://a0.anyrgb.com/pngimg/1506/1690/online-doctor-doctor-woman-examining-baby-doctor-traumatology-doctors-office-doctor-cartoon-cartoon-doctor-male-doctor-female-doctor-medic.png",
               designation: .gastroenterologist,
               experience: "10 YRS EXP",
               qualification: "MBBS, MD, DM (Gasteroentrology)",
               location: "Chennai Medical Centre, Chennai",
               languagesKnown: "English, Tamil, Malayalam",
               availableForAMinimumOf: 7,
               vedioConsultationCost: 800,
               hospitalVisitCost: 800,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "51, 3rd St, KK Nagar West, Nesapakkam Chennai",
               videoConsultTimings: 0,
               hospitalTiming: 0,
               ratings: 4.2,
               totalNumberOfRaters: 15),
        
        Doctor(id: 8,
               name: "Dr. Surabi Dogra Jani",
               imageName: "https://st2.depositphotos.com/3280929/6099/v/600/depositphotos_60994299-stock-illustration-female-doctor-with-clipboard.jpg",
               designation: .gastroenterologist,
               experience: "2 YRS EXP",
               qualification: "MD (pediatrics), Fellow ship in Pediatric Gastroenterology and hepatology",
               location: "Appolo Hospitals, Chennai",
               languagesKnown: "English, Hindi, Marathi, Punjabi",
               availableForAMinimumOf: 7,
               vedioConsultationCost: 1200,
               hospitalVisitCost: 1200,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "Main Plot No. 1 A, Bhat Gidc Estate, Nr. Indira Bridge, Chennai.",
               videoConsultTimings: 0,
               hospitalTiming: 1,
               ratings: 4.7,
               totalNumberOfRaters: 15),
        
//        Dentists
        Doctor(id: 9,
               name: "Dr. Kamalika De",
               imageName: "https://png.pngtree.com/png-clipart/20190120/ourlarge/pngtree-hospital-medical-doctors-cartoon-png-image_491837.jpg",
               designation: .dentist,
               experience: "10 YRS EXP",
               qualification: "BDS, Consultant Esthetic Dentist",
               location: "Shivam Dental Care, Chennai",
               languagesKnown: "English, Bengali, Hindi",
               availableForAMinimumOf: 7,
               vedioConsultationCost: 450,
               hospitalVisitCost: 450,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "Swagatham Complex, Medavakam Main Road, Chennai",
               videoConsultTimings: 0,
               hospitalTiming: 1,
               ratings: 3.8,
               totalNumberOfRaters: 15),
        
        Doctor(id: 10,
               name: "Dr. Aravind Kumar",
               imageName: "https://i.pinimg.com/736x/bb/08/c6/bb08c68f728fce191a4b7e9a19c2344d.jpg",
               designation: .dentist,
               experience: "15 YRS EXP",
               qualification: "BDS",
               location: "The Dentist, Chennai",
               languagesKnown: "English, Hindi, Punjabi",
               availableForAMinimumOf: 3,
               vedioConsultationCost: 200,
               hospitalVisitCost: 200,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "Cc - 1st floor above ICICI Bank ATM, Egmore, Chennai",
               videoConsultTimings: 1,
               hospitalTiming: 0,
               ratings: 4.3,
               totalNumberOfRaters: 15),
        Doctor(id: 11,
               name: "Dr. Dhawal Narang",
               imageName: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7-dxP0GAsryoD4TbeGIfJARNSQlFqDVrK--N-0Sd3dJsLuiNrKuEsQTOL-1q261BMt9g&usqp=CAU",
               designation: .neurologist,
               experience: "5 YRS EXP",
               qualification: "DM-Neurology",
               location: "Appollomedics, Lucknow",
               languagesKnown: "ENglish, Hindi",
               availableForAMinimumOf: 1,
               vedioConsultationCost: 700,
               hospitalVisitCost: 700,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "Chennai - LDA Colony, Sector B",
               videoConsultTimings: 0,
               hospitalTiming: 1,
               ratings: 4.9,
               totalNumberOfRaters: 15),
        Doctor(id: 12,
               name: "Dr. Manasa Attuluri",
               imageName: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSN-OjevTqKS1zJzCjsOf432ElYIIjYDAfygSH0-1_RQEbwe6psQ5v42KZTTHrH9V6Z388&usqp=CAU",
               designation: .neurologist,
               experience: "9 YRS EXP",
               qualification: "MBBS, MD general Medicine, DM Neurology",
               location: "Keerthan Neuro Centre, Medavakam",
               languagesKnown: "English, Hindi, Telugu",
               availableForAMinimumOf: 7,
               vedioConsultationCost: 1200,
               hospitalVisitCost: 800,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "Q.No: Mc -2G, 8 Incline Colony medavakam",
               videoConsultTimings: 1,
               hospitalTiming: 0,
               ratings: 4.0,
               totalNumberOfRaters: 15),
        Doctor(id: 13,
               name: "Dr. Dhiraj Pathak",
               imageName: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFZzPRBMbJ3jevcUYsNTe7Ls4hWL772qIVaE_mhViRZUglo7u7MWX-CK1WGO_oUd1XSXs&usqp=CAU",
               designation: .orthopaedics,
               experience: "35 YRS EXP",
               qualification: "MBBS, D. Ortho",
               location: "Orthomax Orthopedic centre, pallavaram",
               languagesKnown: "English, Hindi, Tamil",
               availableForAMinimumOf: 3,
               vedioConsultationCost: 700,
               hospitalVisitCost: 500,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "Sector 15, Pallavaram",
               videoConsultTimings: 0,
               hospitalTiming: 1,
               ratings: 4.6,
               totalNumberOfRaters: 15),
        Doctor(id: 14,
               name: "Dr. Uma Chandran S",
               imageName: "https://c8.alamy.com/comp/2G3HY6C/female-doctor-with-a-stethoscope-medical-professional-or-therapist-illustration-in-cartoon-style-2G3HY6C.jpg",
               designation: .orthopaedics,
               experience: "45 YRS EXP",
               qualification: "MBBS, FRCS",
               location: "Apollo Hospitals Greams Road, Chennai",
               languagesKnown: "English, Telugu, Tamil",
               availableForAMinimumOf: 4,
               vedioConsultationCost: 800,
               hospitalVisitCost: 1000,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "Greams Lane, 21, Greams Rd, Thousand Lights, Chennai",
               videoConsultTimings: 1,
               hospitalTiming: 0,
               ratings: 4.1,
               totalNumberOfRaters: 15),
        Doctor(id: 15,
               name: "Dr. Priya K",
               imageName: "https://us.123rf.com/450wm/sahaastra/sahaastra2004/sahaastra200400070/146294026-vrouwelijke-arts-draagt-een-medisch-chirurgisch-wegwerpmasker-medische-muts-en-rubberen-handschoenen.jpg?ver=6",
               designation: .dermatologist,
               experience: "22 YRS EXP",
               qualification: "MBBS, MD Dermatology",
               location: "Apollo Hospital Greams Road",
               languagesKnown: "English, Tamil, Telugu, Hindi",
               availableForAMinimumOf: 5,
               vedioConsultationCost: 1500,
               hospitalVisitCost: 1500,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "Greams Lane, 21, Greams Rd, Thousand Lights, Chennai",
               videoConsultTimings: 1,
               hospitalTiming: 0,
               ratings: 4.8,
               totalNumberOfRaters: 15),
        Doctor(id: 16,
               name: "Dr. Ravichandran G",
               imageName: "https://media.istockphoto.com/id/1217656558/ko/%EB%B2%A1%ED%84%B0/%EC%83%9D%EA%B0%81-%EC%9D%98%EC%82%AC-%ED%98%B8%EA%B8%B0%EC%8B%AC-%ED%91%9C%ED%98%84-%ED%98%BC%EB%9E%80-%EA%B6%81%EA%B8%88-%EC%9D%98%EB%A3%8C-%EB%82%A8%EC%84%B1-%EC%9D%B8%EB%AC%BC.jpg?s=1024x1024&w=is&k=20&c=Bn9Lu7TPZHyDnAt-1fxpLkBVmxsTY6ZcFHKzCC-Vvn4=",
               designation: .dermatologist,
               experience: "23 YRS EXP",
               qualification: "Bsc, MD, DD, MDerm",
               location: "Apollo hospital Greams Road",
               languagesKnown: "English, Tamil",
               availableForAMinimumOf: 7,
               vedioConsultationCost: 1000,
               hospitalVisitCost: 1000,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "Greams Lane, 21, Greams Rd, Thousand Lights, Chennai",
               videoConsultTimings: 0,
               hospitalTiming: 1,
               ratings: 4.2,
               totalNumberOfRaters: 15),
        Doctor(id: 17,
               name: "Dr. Srinivas C",
               imageName: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyn0WKj_dfAEMkitUIM3pPddA-a2kh1ccXvJ-e-mhzCIAY_pTUfafCEB1WN0KBhMzWHsw&usqp=CAU",
               designation: .trichologist,
               experience: "27 YRS EXP",
               qualification: "MBBS, Tricology & STD",
               location: "Revive Skin and Hain Clinic, Chennai",
               languagesKnown: "ENglish, Hindi, Kannada",
               availableForAMinimumOf: 6,
               vedioConsultationCost: 700,
               hospitalVisitCost: 700,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "52 - 2, Nanjappa Rd, Opp to Appolo Pharmacy Nanjappa Circle, Chennai",
               videoConsultTimings: 1,
               hospitalTiming: 0,
               ratings: 4.7,
               totalNumberOfRaters: 15),
        Doctor(id: 18,
               name: "Dr. Apoorva Ragavan",
               imageName: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAqvvdkmjEOARIzp7ceI6aJRNoy3vSNLtfCAeeuuVwLqBXh-dFl1Nu-UODLCGiqOQw1Eo&usqp=CAU",
               designation: .trichologist,
               experience: "2 YRS EXP",
               qualification: "MBBS, MD (Tricology)",
               location: "Appolo First Med Hospitals PH Road Chennai",
               languagesKnown: "English",
               availableForAMinimumOf: 4,
               vedioConsultationCost: 700,
               hospitalVisitCost: 700,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "No.154 Poonamalee High Road, Kilpauk Chennai.",
               videoConsultTimings: 0,
               hospitalTiming: 1,
               ratings: 4.0,
               totalNumberOfRaters: 15),
        Doctor(id: 19,
               name: "Dr. Sarika Gupta",
               imageName: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrPDGIKmEBIbWOKGpFwJbq3VMTDfKw6HuCDRCLb8500IPi5kGKeKALf8OXXXj5T6WqSoo&usqp=CAU",
               designation: .gynacologist,
               experience: "15 YRS EXP",
               qualification: "MBBS, MD (OBGYN), Dip(Access Srug)",
               location: "Apollo Hospital Greams Road",
               languagesKnown: "English, Hindi, Tamil",
               availableForAMinimumOf: 7,
               vedioConsultationCost: 1500,
               hospitalVisitCost: 1500,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "Greams Lane, 21, Greams Rd, Thousand Lights, Chennai",
               videoConsultTimings: 1,
               hospitalTiming: 0,
               ratings: 4.3,
               totalNumberOfRaters: 15),
        Doctor(id: 20,
               name: "Dr. Mamta Pattnayak",
               imageName: "https://365psd.com/images/istock/previews/9089/90896103-smiling-doctor-examining-baby-boy.jpg",
               designation: .gynacologist,
               experience: "23 YRS EXP",
               qualification: "MBBS, MD, Gynaecology",
               location: "Apollo Hospital Greams Road",
               languagesKnown: "English, Hindi, Tamil",
               availableForAMinimumOf: 7,
               vedioConsultationCost: 1000,
               hospitalVisitCost: 1000,
               locationImageName: "https://img.freepik.com/free-vector/hospital-clinic-building-with-green-bushes-benches-front-yard-medicine-city-infirmary-health-care-infrastructure-medic-two-storied-office-cityscape-background-cartoon-illustration_107791-3825.jpg?w=2000&t=st=1664706481~exp=1664707081~hmac=2f8a165aceceafc230023a922c07052c706f75a128499ba248fc30b11cc11cba",
               locationAddress: "Greams Lane, 21, Greams Rd, Thousand Lights, Chennai",
               videoConsultTimings: 0,
               hospitalTiming: 1,
               ratings: 4.7,
               totalNumberOfRaters: 15),
    ]
    
    let doctorReviewAndRatings: [DoctorReviewAndRating] = [
        DoctorReviewAndRating(review: Reviews(id: 1,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 1,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 2,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 2,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 3,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 3,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 4,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 4,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 5,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 5,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 6,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 6,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 7,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 7,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 8,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 8,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 9,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 9,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 10,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 10,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 11,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 11,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 12,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 12,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 13,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 13,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 14,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 14,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 15,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 15,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 16,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 16,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 17,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 17,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 18,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 18,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 19,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 19,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
        DoctorReviewAndRating(review: Reviews(id: 20,
                                              title: Rating.medium.doctorRatingDescription,
                                              body: "Great treatment and a friendly doctor to visit to, gives a clear explanation about the problem and gives a proper prescription.",
                                              numberOfRatingStars: 3,
                                              dateOfReview: "21-12-2022",
                                              reviewerName: "Stephen",
                                              category: .doctor),
                              rating: Ratings(id: 20,
                                              numberOfFiveStars: 1,
                                              numberOfFourStars: 2,
                                              numberOfThreeStars: 3,
                                              numberOfTwoStars: 4,
                                              numberOfOneStars: 5,
                                              category: .doctor)),
    ]
    
    let images: [Image] = [
        Image(category: .emergency, link: "https://cdn.iconscout.com/icon/premium/png-256-thumb/cardiac-arrest-3543051-2964206.png"),
        Image(category: .emergency, link: "https://cdn.iconscout.com/icon/premium/png-256-thumb/snake-bite-2638834-2186262.png"),
        Image(category: .emergency, link: "https://static.thenounproject.com/png/4822251-200.png"),
        Image(category: .emergency, link: "https://uxwing.com/wp-content/themes/uxwing/download/health-sickness-organs/injury-icon.png"),
        Image(category: .emergency, link: "https://cdn-icons-png.flaticon.com/512/5360/5360270.png"),
    ]
    
    let contacts: [EmergencyContact] = [
        EmergencyContact(
            firstName: "Miskin",
            lastName: "M",
            number: "9295628467",
            identifier: "hcnpypwemxffcnepfhwpsfh",
            profileImage: nil)
    ]
    
    let ratings: [Ratings] = [
        Ratings(
            id: 1,
            numberOfFiveStars: 3,
            numberOfFourStars: 5,
            numberOfThreeStars: 2,
            numberOfTwoStars: 0,
            numberOfOneStars: 4,
            category: .pharmacy),
        Ratings(
            id: 2,
            numberOfFiveStars: 4,
            numberOfFourStars: 2,
            numberOfThreeStars: 3,
            numberOfTwoStars: 5,
            numberOfOneStars: 3,
            category: .pharmacy),
    ]
    
    let reviews: [Reviews] = [
        Reviews(
            id: 1,
            title: "Overall, Great Store",
            body: "This store is beautiful, fast, and efficient. It has such a great hospitality and its more welcoming when compared to other stores. I have had an amazing experience Thanks!",
            numberOfRatingStars: 4,
            dateOfReview: "May 4, 2022",
            reviewerName: "preston_p",
            category: .pharmacy),
        Reviews(
            id: 1,
            title: "Overall, Great Store",
            body: "This store is very overWhelming and welcoming, feels great to shop both in person and also online.",
            numberOfRatingStars: 3,
            dateOfReview: "May 6, 2022",
            reviewerName: "simson_V",
            category: .pharmacy),
        Reviews(
            id: 2,
            title: "Overall, Great Store",
            body: "This store is very overWhelming and welcoming, feels great to shop both in person and also online. They have a great hospitality.",
            numberOfRatingStars: 3,
            dateOfReview: "May 20, 2022",
            reviewerName: "Suresh",
            category: .pharmacy),
        
    ]
    
    let pharmacies: [Pharmacy] = [
        Pharmacy(
            id: 1,
            name: "Lakma Pharmacy",
            productBatchId: 2,
            address: "No 5/44, Grand Southern Trunk Rd, Peramanur, Singaperumal Koil, Tamil Nadu 603204",
            directionToStoreLink: "https://goo.gl/maps/NfmhsRE4q9Reqeto7",
            kmValue: "2.5 km",
            ratingOutOfFive: 3,
            totalNumberOfRatings: 14,
            ratingId: 1,
            reviewId: 1,
            pharmacyImage: "https://img.freepik.com/premium-vector/drug-store-template-hand-drawn-cartoon-illustration-shop-sale-drugs-pharmacist-medicine_2175-7228.jpg?w=2000"),
        Pharmacy(
            id: 2,
            name: "Sri Krishna Medicals",
            productBatchId: 1,
            address: "Shop No. 2 , GST ROAD,Thailavaram, Potheri, Chennai, Tamil Nadu 603203",
            directionToStoreLink: "https://goo.gl/maps/K5FAHNscY1HWXDNb8",
            kmValue: "3 km",
            ratingOutOfFive: 2,
            totalNumberOfRatings: 17,
            ratingId: 2,
            reviewId: 2,
            pharmacyImage: "https://i0.wp.com/pharmacyequipmentmarketplace.com/wp-content/uploads/2019/12/Pharmacy-Storefront-Logo.jpg?fit=1505%2C1032&ssl=1"),
    ]
    
    let products = [
        PharmacyProduct(
            pharmacyId: 1,
            productId: 1,
            name: "Gabapentin",
            expiryDate: "24 Jul 2025",
            dosage: "100 mg",
            cost: "50.5",
            medDescription: "The anticonvulsant gabapentin is one of the most commonly prescribed medications, and has broad uses. Although still unclear, gabapentin’s mechanism of action involves neuron excitability. It increases gamma aminobutyric acid (GABA) levels to help with pain reduction. It also suppresses the release of norepinephrine, glutamate, and substance P.",
            availableCount: 55,
            imageLink: "https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2022/01/effects_-gabapentin_GettyImages1348724431_Header-800x728.jpg",
            productRating: 4.2,
            totalBuyers: 35000),
        PharmacyProduct(
            pharmacyId: 1,
            productId: 2,
            name: "Amoxicillin",
            expiryDate: "14 May 2025",
            dosage: "250 mg",
            cost: "36.8",
            medDescription: "Like gabapentin, amoxicillin is another commonly prescribed drug. It’s used to treat a gamut of infections, including bronchitis and pneumonia, as well as ear, nose, throat, skin and urinary tract infections. As such, physicians across specialties are comfortable prescribing it. Amoxicillin is usually well-tolerated, but can cause nausea, vomiting, headache, changes in taste, and other unharmful symptoms.",
            availableCount: 150,
            imageLink: "https://wellonapharma.com/admincms/product_img/product_resize_img/amoxicillin-250mg-capsules-manufacturers_1618818051.jpg",
            productRating: 3.5,
            totalBuyers: 40000),
        PharmacyProduct(
            pharmacyId: 1,
            productId: 3,
            name: "Amphotericin B",
            expiryDate: "25 Aug 2029",
            dosage: "50 mg",
            cost: "65.3",
            medDescription: "Amphotericin is a heavy hitter—a drug that is both feared and respected. It is used to treat very severe fungal infections such as fungal meningitis. Its adverse effects are common, quick onset, and lethal; they include fever, hypotension, nausea, vomiting, headache, dyspnea, chills, weakness, and tachypnea. Sometimes these adverse effects occur with subsequent doses.",
            availableCount: 103,
            imageLink: "https://bsmedia.business-standard.com/_media/bs/img/article/2021-05/19/full/1621411720-7003.jpg",
            productRating: 3.0,
            totalBuyers: 23000),
        PharmacyProduct(
            pharmacyId: 1,
            productId: 4,
            name: "Cephalexin",
            expiryDate: "24 Sep 2027",
            dosage: "250 mg",
            cost: "54.3",
            medDescription: "This orally administered first-generation cephalosporin is a useful tool to treat a broad range of infections, including respiratory, genitourinary, ear, and skin and soft tissue, as well as strep throat. Like amoxicillin, it represents another drug that could be an easy fix for physicians of any stripe.",
            availableCount: 230,
            imageLink: "https://5.imimg.com/data5/SELLER/Default/2021/7/YM/QN/ZL/3911030/cephalexin-dispersible-tablets-250-mg-500x500.jpg",
            productRating: 2.7,
            totalBuyers: 15000),
        PharmacyProduct(
            pharmacyId: 1,
            productId: 5,
            name: "Amitriptyline",
            expiryDate: "25 Feb 2025",
            dosage: "10 mg",
            cost: "53.6",
            medDescription: "Chances are that, whatever your specialty, you have encountered patients with depression. If you decide to treat the depression in-house, monotherapy with the tricyclic antidepressant amitriptyline is remarkably effective. Remember to caution your patients that this drug shouldn’t be mixed with alcohol.",
            availableCount: 140,
            imageLink: "https://medworksmedia.com/wp-content/uploads/2018/07/amitriptyline_1.png",
            productRating: 4.5,
            totalBuyers: 50000),
        PharmacyProduct(
            pharmacyId: 2,
            productId: 6,
            name: "Statins",
            expiryDate: "18 Mar 2024",
            dosage: "40 mg",
            cost: "64.7",
            medDescription: "Statins like atorvastatin and simvastatin help prevent heart attack and stroke. But how do they work? Plaques are stabilized or even regressed with statin therapy. Statins’ various mechanisms of action likely include decreased inflammation, enhanced endothelial function, and decreased lipid accumulation around a necrotic lipid core.",
            availableCount: 240,
            imageLink: "https://cdn.consumerlab.com/images/answers/73_image.jpg",
            productRating: 4.2,
            totalBuyers: 35000),
        PharmacyProduct(
            pharmacyId: 2,
            productId: 7,
            name: "Fentanyl",
            expiryDate: "30 Apr 2030",
            dosage: "10 ml",
            cost: "90.0",
            medDescription: "The opioid crisis has changed the fabric of American society. It’s swallowed whole communities, and disproportionately impacted the disenfranchised. Here’s one to beware of and avoid at all costs: Fentanyl is 50 to 100 times stronger than morphine, and contributes to more than half of American drug overdose deaths in some states.",
            availableCount: 345,
            imageLink: "https://nida.nih.gov/sites/default/files/2020-05/Fentanyl-ALT.jpg",
            productRating: 3.5,
            totalBuyers: 40000),
        PharmacyProduct(
            pharmacyId: 2,
            productId: 8,
            name: "Tetracycline",
            expiryDate: "25 Aug 2026",
            dosage: "500 mg",
            cost: "95.4",
            medDescription: "Inflammatory acne is commonly treated with tetracycline. But, this potent antibiotic has a slew of nasty side effects frequent among users, including gastrointestinal upset, skin rashes, fever, photosensitivity (ie, sunburn), It also shouldn’t be taken by pregnant women because exposure to the fetus can result in permanent yellow-gray tooth discoloration.",
            availableCount: 456,
            imageLink: "https://5.imimg.com/data5/SELLER/Default/2021/5/YM/RR/EI/74288016/tetracycline-hydrochloride-500x500.png",
            productRating: 3.0,
            totalBuyers: 23000),
        PharmacyProduct(
            pharmacyId: 2,
            productId: 9,
            name: "Warfarin",
            expiryDate: "16 Sep 2023",
            dosage: "2 mg",
            cost: "84.9",
            medDescription: "Did you know that some rat poisons contain the blood-thinner warfarin (Coumadin)? When rats squeeze through little holes and crevices they break blood vessels and bleed to death. Which brings to mind how warfarin was discovered in the first place. In the prairies of Depression-era America, cattle began to die from internal bleeding with no overt cause.",
            availableCount: 346,
            imageLink: "https://tajpharma.in/wp-content/uploads/cache/images/Warfarin-sodium-tablets-in-india-2-scaled/Warfarin-sodium-tablets-in-india-2-scaled-3274572246.jpg",
            productRating: 2.7,
            totalBuyers: 15000),
        PharmacyProduct(
            pharmacyId: 2,
            productId: 10,
            name: "Metformin",
            expiryDate: "18 Oct 2027",
            dosage: "500 mg",
            cost: "93.2",
            medDescription: "This drug is the most commonly prescribed drug for type 2 diabetes, which makes sense because it is cheap and generic. You may think that metformin is a no-brainer as a first-line therapy, but lots of people can’t stomach it because of gastrointestinal disturbance, including diarrhea, flatulence, stomach pain, nausea, and vomiting. ",
            availableCount: 457,
            imageLink: "https://images.ctfassets.net/4w8qvp17lo47/6vXaH4Y5Gw6AMEmASwGkc6/e6ff962a82811e4d160cc2d5c0d8b3cb/metformin-antidiabetic-tablets-science-photo-library.jpg",
            productRating: 4.5,
            totalBuyers: 50000)
    ]
    
    let paymentOptions: [CardDetails] = [
        CardDetails(cardType: .applePay,
                    cardName: PaymentType.applePay.typeName,
                    cardNumber: "1111 2222 3333 4444",
                    expiryDate: "",
                    cvvNumber: ""),
        
        CardDetails(cardType: .googlePay,
                    cardName: PaymentType.googlePay.typeName,
                    cardNumber: "1111 2222 3333 4444",
                    expiryDate: "",
                    cvvNumber: ""),
        CardDetails(cardType: .payPal,
                    cardName: PaymentType.payPal.typeName,
                    cardNumber: "1111 2222 3333 4444",
                    expiryDate: "",
                    cvvNumber: "")
    ]
    
    let consultations: [ConsultationUpdater] = [
        ConsultationUpdater(
            doctorId: 1,
            consultationDate: "28 Oct, 2022",
            consultationTime: "10:00 AM",
            patientName: "Mr.X",
            patientGender: "Male",
            patientAge: "22",
            patientProblem: "Pain in the chest region",
            packageInfomation: .hospitalVisit,
            cost: "Rs. 300",
            status: .upcoming,
            forUserId: 1),
        
        ConsultationUpdater(
            doctorId: 5,
            consultationDate: "30 Oct, 2022",
            consultationTime: "12:00 AM",
            patientName: "Mr.Y",
            patientGender: "Male",
            patientAge: "22",
            patientProblem: "Pain in the chest region",
            packageInfomation: .hospitalVisit,
            cost: "Rs. 300",
            status: .completed,
            forUserId: 2),
        
        ConsultationUpdater(
            doctorId: 7,
            consultationDate: "31 Oct, 2022",
            consultationTime: "03:00 PM",
            patientName: "Mr.Z",
            patientGender: "Female",
            patientAge: "22",
            patientProblem: "Pain in the chest region",
            packageInfomation: .hospitalVisit,
            cost: "Rs. 300",
            status: .cancelled,
            forUserId: 3),
    ]
    
    let hospitals: [Hospital] = [
        Hospital(id: 0,
                 name: "Gleneagles Global",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipPFWQtZ2WJt9CON8f3sBs6jwk5vJVTuddJgmmwR=w426-h240-k-no",
                 ratings: 4.5,
                 openHours: "24 Hours",
                 address: "439, Embassy Residency Rd, Cheran Nagar, Perumbakkam, Chennai, Tamil Nadu 600100",
                 place: .chennai,
                 directionLink: "https://goo.gl/maps/Jd2j2au9KHVKCfRm9"),
        Hospital(id: 1,
                 name: "Lifeline",
                 imageLink: "https://www.google.com/maps/place/Lifeline+Hospitals/@13.0782897,80.2336873,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipMGivhL4f_qq4icx5i25ZQvHQlMh6kG1m6wlJ1i!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMGivhL4f_qq4icx5i25ZQvHQlMh6kG1m6wlJ1i%3Dw217-h100-k-no!7i4000!8i1840!4m6!3m5!1s0x3a52667fb51df4c1:0xda54eb8cae181334!8m2!3d13.0782897!4d80.2336873!16s%2Fg%2F1hm1y1h9f#",
                 ratings: 4.8,
                 openHours: "24 Hours",
                 address: "47/3, New Avadi Rd, Alagappa Nagar, Kilpauk, Chennai, Tamil Nadu 600010",
                 place: .chennai,
                 directionLink: "https://goo.gl/maps/PjSFyeHHhCgb27dg9"),
        Hospital(id: 2,
                 name: "Fortis Malar",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipPPZDI3PRhbPwzdFLE6j4kFhIW4ZcKyPbNMgaUZ=w408-h544-k-no",
                 ratings: 4.2,
                 openHours: "24 Hours",
                 address: "No. 52, 1st Main Rd, Gandhi Nagar, Adyar, Chennai, Tamil Nadu 600020",
                 place: .chennai,
                 directionLink: "https://goo.gl/maps/Kbpb326Lr3estaur8"),
        Hospital(id: 3,
                 name: "Rela",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipMCDb175vuGF5Muqn2LqUMEWKHhDggL5-0-Nj_q=w408-h306-k-no",
                 ratings: 4.7,
                 openHours: "24 Hours",
                 address: "7, CLC Works Rd, Nagappa Nagar, Chromepet, Chennai, Tamil Nadu 600044",
                 place: .chennai,
                 directionLink: "https://goo.gl/maps/gLwL3AUD1aM8M3St7"),
        Hospital(id: 4,
                 name: "Apollo",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipPCkBeEKi13rwWZXOFeCU2AXJKkL9RhzpJm8RDK=w408-h544-k-no",
                 ratings: 4.8,
                 openHours: "24 Hours",
                 address: "Plot No, 64, Vanagaram-Ambattur Rd, Ayanambakkam, Ambattur Industrial Estate, Chennai, Tamil Nadu 600095",
                 place: .chennai,
                 directionLink: "https://goo.gl/maps/giYBdgRrx7p8gnor8"),
        Hospital(id: 5,
                 name: "Sri Ramakrishna",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipMnpcOVdbvbcelBss52qvSxXccV299kuPPqHVR_=w408-h306-k-no",
                 ratings: 4.0,
                 openHours: "24 Hours",
                 address: "395, Sarojini Naidu Rd, Siddhapudur, Balasundaram Layout, B.K.R Nagar, Coimbatore, Tamil Nadu 641044",
                 place: .coimbatore,
                 directionLink: "https://goo.gl/maps/3NbCFQrSJAJ2qyA26"),
        Hospital(id: 6,
                 name: "KG",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipPZt_LXgIJwj5_cjQmhzXh32yArbzRuJnxhBCFE=w408-h264-k-no",
                 ratings: 4.4,
                 openHours: "24 Hours",
                 address: "5, Government Arts College Rd, Opposite Court, Gopalapuram, Coimbatore, Tamil Nadu 641018",
                 place: .coimbatore,
                 directionLink: "https://goo.gl/maps/777j8RD2YWLzaJUX6"),
        Hospital(id: 7,
                 name: "Rao",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipMTRkH7gjV3sTEJD0IvjAld_-JNIvyENkCVVsgN=w426-h240-k-no",
                 ratings: 4.7,
                 openHours: "24 Hours",
                 address: "120, W Periasamy Rd, R.S. Puram, Coimbatore, Tamil Nadu 641002",
                 place: .coimbatore,
                 directionLink: "https://goo.gl/maps/AJFyukyHAYJs7Aqf6"),
        Hospital(id: 8,
                 name: "Kongunad",
                 imageLink: "https://www.google.com/maps/place/Kongunad+Hospital/@11.0177027,76.9602551,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipNFxDiRsGmyfGbjl1oncUPrPdM3iqGEA9sjMUvT!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipNFxDiRsGmyfGbjl1oncUPrPdM3iqGEA9sjMUvT%3Dw203-h152-k-no!7i4032!8i3024!4m6!3m5!1s0x3ba85f2d2d7ea4f5:0x917177ee60a653c6!8m2!3d11.0177156!4d76.9605021!16s%2Fg%2F1tdx2krl#",
                 ratings: 4.8,
                 openHours: "24 Hours",
                 address: "11th Street, Opp:, E Power House Rd, Tatabad, Coimbatore, Tamil Nadu 641012",
                 place: .coimbatore,
                 directionLink: "https://goo.gl/maps/SjevTjLpteLqDqAt8"),
        Hospital(id: 9,
                 name: "FIMS",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipMHQR9LZDlUZT4wIounBoqHCO70ajYJMFYWfQtP=w408-h271-k-no",
                 ratings: 4.5,
                 openHours: "24 Hours",
                 address: "193, 145, Pollachi Main Rd, Sundarapuram, Coimbatore, Tamil Nadu 641024",
                 place: .coimbatore,
                 directionLink: "https://goo.gl/maps/ZxZ4PKruCShUW6h37"),
        Hospital(id: 10,
                 name: "Aster CMI",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipMjE5VM92ezXspwl0KEHDHNHUekDk6LIhOlRJfi=w495-h240-k-no",
                 ratings: 4.7,
                 openHours: "24 Hours",
                 address: "No. 43/2, New Airport Road NH 7, Dr Puneeth Rajkumar Rd, Sahakar Nagar, Bengaluru, Karnataka 560092",
                 place: .bangalore,
                 directionLink: "https://goo.gl/maps/bH8pS9mdcqFMiE3AA"),
        Hospital(id: 11,
                 name: "Manipal",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipOF0bEeck4fZxTIYF2jIFn0XHY-eo2ZqMcao8lU=w408-h541-k-no",
                 ratings: 4.6,
                 openHours: "24 Hours",
                 address: "98, HAL Old Airport Rd, Kodihalli, Bengaluru, Karnataka 560017",
                 place: .bangalore,
                 directionLink: "https://goo.gl/maps/mhivQF718rxPHR4A6"),
        Hospital(id: 12,
                 name: "Re life hospital",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipPP7iYQH1YEgs3cz7wD494e7myN8B2Iy4V9H5A_=w408-h240-k-no-pi0-ya39.790005-ro-0-fo100",
                 ratings: 4.8,
                 openHours: "24 Hours",
                 address: "No 208 & 209, Dr Puneeth Rajkumar Rd, Banashankari 3rd Stage, Bengaluru, Karnataka 560085",
                 place: .bangalore,
                 directionLink: "https://goo.gl/maps/vnVZHUwxg8PCvPnL8"),
        Hospital(id: 13,
                 name: "Cura",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipN6XRFNJOXH2Bq0NzHx5T5A3KuRw1yAQkx72M_W=w408-h274-k-no",
                 ratings: 4.6,
                 openHours: "24 Hours",
                 address: "18, Kanakapura Rd, Venkatareddy Layout, Industrial Area, Doddakallasandra, Uttarahalli Hobli, Bengaluru, Karnataka 560062",
                 place: .bangalore,
                 directionLink: "https://goo.gl/maps/cLBANQC1AkQ873Po9"),
        Hospital(id: 14,
                 name: "Spurthy",
                 imageLink: "https://www.google.com/maps/place/Spurthy+Hospital+-+Best+Hospital+in+BTM,+BTM+Layout,+Near+Me+BTM/@12.9237863,77.6113157,3a,77.1y,90t/data=!3m8!1e2!3m6!1sAF1QipPUzlfYmdSpI7mYutU5wQhBUiGU_3_Swt6-YN4L!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipPUzlfYmdSpI7mYutU5wQhBUiGU_3_Swt6-YN4L%3Dw249-h100-k-no!7i1349!8i540!4m6!3m5!1s0x3bae14559a0550cb:0xd34d84a4d288974e!8m2!3d12.9239013!4d77.6113542!16s%2Fg%2F1tf7k_jg#",
                 ratings: 4.7,
                 openHours: "24 Hours",
                 address: "Taverekere, 22, Chocolate Factory Rd, BTM 1st Stage, Bengaluru, Karnataka 560029",
                 place: .bangalore,
                 directionLink: "https://goo.gl/maps/noWNfhVeybMAL2NH7"),
        Hospital(id: 15,
                 name: "S L Raheja",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipPLuL0SZzG9OW60N8cv-xA53aNlrsb0PNY6Ezy8=w408-h544-k-no",
                 ratings: 4.5,
                 openHours: "24 Hours",
                 address: "Raheja Rugnalaya Marg, Mahim West, Mahim, Mumbai, Maharashtra 400016",
                 place: .mumbai,
                 directionLink: "https://goo.gl/maps/sdpD4GGhynA6GrGp9"),
        Hospital(id: 16,
                 name: "Saifee",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipNXOFGUKAmNznWitI-Nq8yUH8i5pG-V8wdHylc=w408-h544-k-no",
                 ratings: 4.0,
                 openHours: "24 Hours",
                 address: "Saifee Hospital, 15/17, Maharshi Karve Rd, opposite Charni Road, Charni Road East, Opera House, Station, Mumbai, Maharashtra 400004",
                 place: .mumbai,
                 directionLink: "https://goo.gl/maps/NqysPDeDqjxRuwQ56"),
        Hospital(id: 17,
                 name: "Wockhardt",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipNuSFzXUIvg-5rihnHHVv4DBFRnI6OUYx-Lxntp=w408-h543-k-no",
                 ratings: 4.5,
                 openHours: "24 Hours",
                 address: "Police Station, 1877, Dr Anandrao Nair Marg, Near Agripada, Mumbai Central, Mumbai, Maharashtra 400011",
                 place: .mumbai,
                 directionLink: "https://goo.gl/maps/F9NUzqf4BN2bqPnP9"),
        Hospital(id: 18,
                 name: "Parakh",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipO4OXGvqKpJQ8ozXLY54za_pTfpa-5-d0-LluvG=w432-h240-k-no",
                 ratings: 4.5,
                 openHours: "24 Hours",
                 address: "Khokani Lane, Opp. Ghatkopar Railway Station, Ghatkopar East, Mumbai, Maharashtra 400077",
                 place: .mumbai,
                 directionLink: "https://goo.gl/maps/FheMXnmp2Bxrrdt3A"),
        Hospital(id: 19,
                 name: "Zynova Shalby",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipNC7mHcHfbUNNAJKJlrLL08pa_4KjJkMCmWI1vb=w408-h280-k-no",
                 ratings: 4.7,
                 openHours: "24 Hours",
                 address: "Acme Elanza, 1900, 1917, Ghatkopar West, Maharashtra 400086",
                 place: .mumbai,
                 directionLink: "https://goo.gl/maps/7eRjtXAZTEsh8ND3A"),
        Hospital(id: 20,
                 name: "Germanten",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipNdV0JBqSFfzUIcyp_f06VdFT5BbsOPLqcHvU6i=w426-h240-k-no",
                 ratings: 4.9,
                 openHours: "24 Hours",
                 address: "# 4-8-138/1/B, opp:Pillar No 150, Attapur, Telangana 500048",
                 place: .hyderabad,
                 directionLink: "https://goo.gl/maps/gAyuvC24RhGSuWEu6"),
        Hospital(id: 21,
                 name: "PACE",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipOEF8b19pysO4wSYIvCrtip6xWqpON8vjDvLXDV=w408-h544-k-no",
                 ratings: 4.5,
                 openHours: "24 Hours",
                 address: "Metro Pillar Number C1775, 18, Hitech City Rd, HUDA Techno Enclave, HITEC City, Hyderabad, Telangana 500081",
                 place: .hyderabad,
                 directionLink: "https://goo.gl/maps/zVhDYczAS9Pm5nzs9"),
        Hospital(id: 22,
                 name: "Virinchi",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipPjqeBcvTVqx4og4Z9WK1xZUzrsWoOBG6qkMahp=w408-h306-k-no",
                 ratings: 4.3,
                 openHours: "24 Hours",
                 address: "Virinchi Circle 8-2-672/5-6, Rd Number 1, Shyam Rao Nagar, Banjara Hills, Hyderabad, Telangana 500034",
                 place: .hyderabad,
                 directionLink: "https://goo.gl/maps/2VBvwY7KR4rZQ4Lo8"),
        Hospital(id: 23,
                 name: "Himagiri",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipPX1pquKT1ChXbrRYsgsaMNEEOBrqui5sndJfoJ=w408-h459-k-no",
                 ratings: 4.1,
                 openHours: "24 Hours",
                 address: "plot no 4, 5,23 & 24, Old Mumbai Hwy, Indira Nagar, Gachibowli, Hyderabad, Telangana 500032",
                 place: .hyderabad,
                 directionLink: "https://goo.gl/maps/bmD3WQeezbHwz4h26"),
        Hospital(id: 24,
                 name: "Prathima",
                 imageLink: "https://lh5.googleusercontent.com/p/AF1QipPeZmu9nwKRwX3QAbUEqR6YJladrN8WW6CF1cLi=w408-h318-k-no",
                 ratings: 4.5,
                 openHours: "24 Hours",
                 address: "3/4/3, Kachiguda Station Rd, Barkatpura, Kachiguda, Hyderabad, Telangana 500027",
                 place: .hyderabad,
                 directionLink: "https://goo.gl/maps/dqD46xZ7VuG95U2S9"),
    ]
    
    var carts:[Cart] = []
    
    init() {
        carts = [
            Cart(productName: products[0].name,
                 productImage: products[0].imageLink,
                 productCost: products[0].cost,
                 productQuantity: 20,
                 pharmacyId: products[0].pharmacyId,
                 productId: products[0].productId,
                 date: "21-01-2023",
                 productRating: products[0].productRating,
                 productStatus: .productPurchased,
                 forUserId: 1),
            
            Cart(productName: products[1].name,
                 productImage: products[1].imageLink,
                 productCost: products[1].cost,
                 productQuantity: 20,
                 pharmacyId: products[1].pharmacyId,
                 productId: products[1].productId,
                 date: "20-01-2022",
                 productRating: products[1].productRating,
                 productStatus: .productPurchased,
                 forUserId: 1),
            
            Cart(productName: products[2].name,
                 productImage: products[2].imageLink,
                 productCost: products[2].cost,
                 productQuantity: 20,
                 pharmacyId: products[2].pharmacyId,
                 productId: products[2].productId,
                 date: "19-01-2022",
                 productRating: products[2].productRating,
                 productStatus: .productPurchased,
                 forUserId: 1),
            
            Cart(productName: products[3].name,
                 productImage: products[3].imageLink,
                 productCost: products[3].cost,
                 productQuantity: 20,
                 pharmacyId: products[3].pharmacyId,
                 productId: products[3].productId,
                 date: "18-01-2022",
                 productRating: products[3].productRating,
                 productStatus: .productPurchased,
                 forUserId: 1),
            
            Cart(productName: products[4].name,
                 productImage: products[4].imageLink,
                 productCost: products[4].cost,
                 productQuantity: 20,
                 pharmacyId: products[4].pharmacyId,
                 productId: products[4].productId,
                 date: "17-01-2022",
                 productRating: products[4].productRating,
                 productStatus: .productPurchased,
                 forUserId: 1),
        ]
        
        loadContents()
    }
    
    func loadContents() {
        
        DBManager.sharedInstance.emptyReminderTable()
        DBManager.sharedInstance.emptyDoctorTables()
        DBManager.sharedInstance.emptyImagesTable()
        DBManager.sharedInstance.emptyEmergencyContactTable()
        DBManager.sharedInstance.emptyRatingTable()
        DBManager.sharedInstance.emptyReviewTable()
        DBManager.sharedInstance.emptyPharmacyTable()
        DBManager.sharedInstance.emptyProductTable()
        DBManager.sharedInstance.emptyPaymentOptionsTable()
        DBManager.sharedInstance.emptyConsultationTable()
        DBManager.sharedInstance.emptyCartTable(forState: .productPurchased, foruserId: UserDefaults.standard.integer(forKey: "User - Id"))
        DBManager.sharedInstance.emptyCartTable(forState: .productUnPurchased, foruserId: UserDefaults.standard.integer(forKey: "User - Id"))
        DBManager.sharedInstance.emptyShippingAddressTable()
        DBManager.sharedInstance.emptyHospitalTable()


        for reminder in reminders{
            DBManager.sharedInstance.addRowToReminder(reminder)
        }

        let array: [Reminder] = DBManager.sharedInstance.getRowsFromReminderTable(forUserId: UserDefaults.standard.integer(forKey: "User - Id"))

        for i in array{
            print(i)
        }

        for doctorVedioCallTiming in doctorVedioCallTimings {
            DBManager.sharedInstance.addAvailableVideoCallTimings(doctorVedioCallTiming)
        }

        for doctorHospitalVisitTiming in doctorHospitalVisitTimings {
            DBManager.sharedInstance.addAvailableHospitalTimings(doctorHospitalVisitTiming)
        }

        for doctor in doctors {
            DBManager.sharedInstance.addDoctorDetailsToTable(doctor)
        }

        for doctorReviewAndRating in doctorReviewAndRatings {
            DBManager.sharedInstance.addDoctorReviewsAndRatingsToTable(doctorReviewAndRating)
        }

        print("Displaying doctor Details")

        let newDoctors: [Doctor] = DBManager.sharedInstance.getRowsFromDoctorTable()

        for doctor in newDoctors {
            print(doctor)
        }

        print("Displaying timing details")

        let shiftTiming1 = DBManager.sharedInstance.getRowsFromTimingsTable(forTable: .availableVideoCallTimings, index: newDoctors[0].videoConsultTimings)

        let shiftTiming2 = DBManager.sharedInstance.getRowsFromTimingsTable(forTable: .availableHospitalTimings, index: newDoctors[0].hospitalTiming)

        print(shiftTiming1!)
        print(shiftTiming2!)

        for image in images {
            DBManager.sharedInstance.addImage(category: image.category, link: image.link)
        }

        for contact in contacts {
            DBManager.sharedInstance.addEmergenyContact(contact)
        }

        for rating in ratings {
            DBManager.sharedInstance.addRating(rating)
        }

        for review in reviews {
            DBManager.sharedInstance.addReview(review)
        }

        let rating = DBManager.sharedInstance.getRowsFromRatingTable(forId: 1, forCategoryId: RatingAndReviewCategory.pharmacy.rawValue)
        let review = DBManager.sharedInstance.getRowsFromReviewTable(forId: 1, forCategoryId: RatingAndReviewCategory.pharmacy.rawValue)

        print("Ratings \n", rating)
        print("Reviews \n", review)

        for pharmacy in pharmacies {
            DBManager.sharedInstance.addPharmacy(pharmacy)
        }

        let pharmacy = DBManager.sharedInstance.getRowsFromPharmacyTable()
        print("Pharmacies \n", pharmacy)

        for product in products {
            DBManager.sharedInstance.addProduct(product)
        }

        print(DBManager.sharedInstance.getRowsFromProductTable(forPharmacyId: 1, forProductId: 1))

        for paymentOption in paymentOptions {
            DBManager.sharedInstance.addPaymentOption(paymentOption)
        }

        for consultation in consultations {
            DBManager.sharedInstance.addConsultation(consultation)
        }

        let consultation = DBManager.sharedInstance.getRowsFromConsultationTable(for: .upcoming, forUserId: UserDefaults.standard.integer(forKey: "User - Id"))

        print(consultation)
        
        for hospital in hospitals {
            DBManager.sharedInstance.addToHospitalTable(hospital)
        }
        
        for cart in carts {
            DBManager.sharedInstance.addToCart(cart)
        }
        
        DBManager.sharedInstance.addPersonDetails(Person(id: 1, name: "Nabushan B", dateOfBirth: "12-Jan-2000", gender: "Male"))
        
        DBManager.sharedInstance.addToShippingAddress(ShippingAddress(id: 1, name: "Nabushan B", contactNumber: "9442619108", doorNumber: "57 A", addressLine1: "Estancia Building", addressLine2: "Chennai", pincode: "600001", forUserId: 1))
        
        DBManager.sharedInstance.addUserDetails(User(id: 1, name: "Nabushan B", password: "Yellow@1412", mailId: "nabushan@gmail.com", dateOfBirth: "11-06-2000"))
    }
}
